# Generated by Django 3.2.4 on 2021-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=160)),
                ('Email', models.CharField(max_length=160)),
                ('password', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'learningpoint_newusers',
            },
        ),
    ]
