# Generated by Django 3.1 on 2021-08-28 08:57

import datetime
from django.db import migrations, models
import learningpoint.models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newusers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 57, 28, 104694)),
        ),
        migrations.AddField(
            model_name='newusers',
            name='expert',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='newusers',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newusers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=learningpoint.models.filepath),
        ),
        migrations.AddField(
            model_name='newusers',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='newusers',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='newusers',
            name='point',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='Username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='password',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
