# Generated by Django 3.1 on 2021-09-06 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpoint', '0002_auto_20210828_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisherId', models.CharField(max_length=20)),
                ('publisherName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3072)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users_post',
            },
        ),
        migrations.AlterField(
            model_name='newusers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 0, 38, 30, 67372)),
        ),
    ]
